"""Domain services encapsulating core policies."""
from __future__ import annotations

from dataclasses import dataclass
import re

from .entities import BusinessLogicImplementation, StepImplementation, StepTask, TestExecution


@dataclass
class StepGenerationResult:
    """Result tuple combining all pieces generated by the agent."""

    step_impl: StepImplementation
    logic_impl: BusinessLogicImplementation
    tests: TestExecution


class StepGenerationService:
    """Pure-domain service that shapes method names and file locations."""

    def determine_step_file(self, task: StepTask) -> str:
        feature_class = self._to_pascal_case(task.feature_name.replace(' ', ''))
        return f"tests/CareSync.Specs/StepDefinitions/{feature_class}Steps.cs"

    def generate_method_name(self, task: StepTask) -> str:
        clean_text = re.sub(r'[<>"]', '', task.step_text)
        words = re.sub(r'[^a-zA-Z0-9]', ' ', clean_text).split()[:6]
        return task.step_type + ''.join(word.capitalize() for word in words if word)

    def determine_service_location(self, task: StepTask) -> str:
        feature_lower = task.feature_name.lower()
        mapping = {
            'symptom': 'SymptomService',
            'medication': 'MedicationService',
            'behavior': 'BehaviorService',
            'nutrition': 'NutritionService',
            'auth': 'AuthenticationService',
            'login': 'AuthenticationService',
            'message': 'CommunicationService',
            'communication': 'CommunicationService',
            'translation': 'TranslationService',
            'nlp': 'NLPService',
            'natural language': 'NLPService',
        }
        for keyword, service in mapping.items():
            if keyword in feature_lower:
                return f"src/3-Infrastructure/CareSync.Infrastructure/Services/{service}.cs"
        return 'src/3-Infrastructure/CareSync.Infrastructure/Services/GenericService.cs'

    def build_step_implementation(self, task: StepTask) -> StepImplementation:
        file_path = self.determine_step_file(task)
        method_name = self.generate_method_name(task)
        notes = f"Generated definition for {task.step_type} step"
        return StepImplementation(file_path, method_name, notes)

    def build_logic_implementation(self, task: StepTask) -> BusinessLogicImplementation:
        location = self.determine_service_location(task)
        notes = f"Implemented business logic in {location}"
        return BusinessLogicImplementation(location, notes)

    def simulate_tests(self) -> TestExecution:
        return TestExecution(True, True, 'All tests passed (simulated)')

    def _to_pascal_case(self, text: str) -> str:
        words = re.sub(r'[^a-zA-Z0-9]', ' ', text).split()
        return ''.join(word.capitalize() for word in words if word)

