#!/usr/bin/env python3
"""
Pull Request Manager
Creates and manages GitHub pull requests for agent changes
"""

import os
import subprocess
import logging
import json
from typing import Optional, Dict
from pathlib import Path


class PullRequestManager:
    """
    Manages GitHub pull requests for automated agent commits.

    Uses GitHub CLI (gh) to create PRs and interact with CodeRabbit.
    """

    def __init__(self, repo_path: str, base_branch: str = "main"):
        """
        Initialize the PR manager.

        Args:
            repo_path: Path to the git repository
            base_branch: Base branch for PRs (default: main)
        """
        self.repo_path = Path(repo_path).resolve()
        self.base_branch = base_branch

        # Verify gh CLI is installed
        if not self._check_gh_installed():
            raise RuntimeError("GitHub CLI (gh) is not installed. Install: brew install gh")

        # Verify authentication
        if not self._check_gh_auth():
            raise RuntimeError("GitHub CLI not authenticated. Run: gh auth login")

    def create_pull_request(
        self,
        branch_name: str,
        task: Dict,
        worktree_path: Path
    ) -> Optional[str]:
        """
        Create a pull request for the agent's changes.

        Args:
            branch_name: Branch name containing changes
            task: Task dictionary with metadata
            worktree_path: Path to the worktree

        Returns:
            PR URL if successful, None otherwise
        """
        # Generate PR title and body
        title = self._generate_pr_title(task)
        body = self._generate_pr_body(task)

        logging.info(f"Creating pull request for branch: {branch_name}")
        logging.debug(f"PR Title: {title}")

        try:
            # Create PR using gh CLI
            result = subprocess.run(
                [
                    "gh", "pr", "create",
                    "--base", self.base_branch,
                    "--head", branch_name,
                    "--title", title,
                    "--body", body,
                    "--label", "BDD",
                    "--label", "automated",
                    "--label", "agent-generated"
                ],
                cwd=worktree_path,
                capture_output=True,
                text=True,
                check=True
            )

            pr_url = result.stdout.strip()
            logging.info(f"✓ Pull request created: {pr_url}")

            # Add CodeRabbit review request
            self._request_coderabbit_review(pr_url, worktree_path)

            return pr_url

        except subprocess.CalledProcessError as e:
            logging.error(f"✗ Failed to create pull request: {e}")
            logging.error(f"stderr: {e.stderr}")
            return None

    def _generate_pr_title(self, task: Dict) -> str:
        """
        Generate PR title from task.

        Args:
            task: Task dictionary

        Returns:
            PR title
        """
        step_type = task.get('step_type', 'Step')
        step_text = task.get('step_text', '')[:60]
        feature_name = task.get('feature_name', 'Feature')

        return f"feat(BDD): {step_type} {step_text}"

    def _generate_pr_body(self, task: Dict) -> str:
        """
        Generate PR body with task details.

        Args:
            task: Task dictionary

        Returns:
            PR body in markdown
        """
        feature_name = task.get('feature_name', 'N/A')
        scenario_name = task.get('scenario_name', 'N/A')
        step_type = task.get('step_type', 'N/A')
        step_text = task.get('step_text', 'N/A')
        task_id = task.get('task_id', 'N/A')

        body = f"""## BDD Step Implementation

**Feature:** {feature_name}
**Scenario:** {scenario_name}
**Step:** {step_type} {step_text}
**Task ID:** `{task_id}`

### Changes

This PR implements a single BDD step definition along with its supporting business logic.

### Implementation Details

- ✅ Step definition created in SpecFlow
- ✅ Business logic implemented
- ✅ Build passes with zero warnings
- ✅ No regressions detected
- ✅ Follows CLAUDE.md coding standards

### Code Quality

- No magic strings or magic numbers (enums/constants used)
- Comprehensive XML documentation
- Primary constructors and records for immutable objects
- No inline comments (XML docs only)

### Testing

Expected test behavior:
- ✅ This step should pass when fully implemented
- ⚠️ Other steps in scenario may still be pending (expected for incremental BDD)

### Review Instructions

This is an automated PR generated by the Claude Code agent system. Please review:

1. Code quality and adherence to standards
2. Correctness of BDD step implementation
3. Business logic soundness
4. Any missing edge cases

---

🤖 **Generated by Claude Code Agent System**
📊 **Agent Version:** 2.0 (Parallel Worktree Edition)
"""

        return body

    def _request_coderabbit_review(self, pr_url: str, worktree_path: Path):
        """
        Request a CodeRabbit review for the PR.

        Args:
            pr_url: URL of the pull request
            worktree_path: Path to worktree
        """
        try:
            # Extract PR number from URL
            pr_number = pr_url.split('/')[-1]

            # Add comment to trigger CodeRabbit
            comment = "@coderabbitai review"

            subprocess.run(
                [
                    "gh", "pr", "comment", pr_number,
                    "--body", comment
                ],
                cwd=worktree_path,
                capture_output=True,
                text=True,
                check=True
            )

            logging.info(f"✓ CodeRabbit review requested for PR #{pr_number}")

        except subprocess.CalledProcessError as e:
            logging.warning(f"⚠ Failed to request CodeRabbit review: {e}")

    def get_pr_status(self, pr_number: str) -> Optional[Dict]:
        """
        Get the current status of a pull request.

        Args:
            pr_number: PR number

        Returns:
            Dict with PR status information or None if failed
        """
        try:
            result = subprocess.run(
                [
                    "gh", "pr", "view", pr_number,
                    "--json", "state,mergeable,reviewDecision,reviews,comments,updatedAt"
                ],
                cwd=self.repo_path,
                capture_output=True,
                text=True,
                check=True
            )

            return json.loads(result.stdout)

        except subprocess.CalledProcessError as e:
            logging.error(f"Failed to get PR status: {e}")
            return None

    def get_review_comments(self, pr_number: str) -> list:
        """
        Get all review comments for a PR.

        Args:
            pr_number: PR number

        Returns:
            List of review comment dicts
        """
        try:
            result = subprocess.run(
                [
                    "gh", "api",
                    f"/repos/{{owner}}/{{repo}}/pulls/{pr_number}/comments"
                ],
                cwd=self.repo_path,
                capture_output=True,
                text=True,
                check=True
            )

            comments = json.loads(result.stdout)
            return comments

        except subprocess.CalledProcessError as e:
            logging.error(f"Failed to get review comments: {e}")
            return []

    def merge_pull_request(self, pr_number: str, method: str = "squash") -> bool:
        """
        Merge a pull request.

        Args:
            pr_number: PR number
            method: Merge method (squash, merge, rebase)

        Returns:
            True if successful, False otherwise
        """
        try:
            subprocess.run(
                [
                    "gh", "pr", "merge", pr_number,
                    f"--{method}",
                    "--auto"  # Auto-merge when checks pass
                ],
                cwd=self.repo_path,
                capture_output=True,
                text=True,
                check=True
            )

            logging.info(f"✓ Pull request #{pr_number} merged successfully")
            return True

        except subprocess.CalledProcessError as e:
            logging.error(f"✗ Failed to merge PR #{pr_number}: {e}")
            return False

    @staticmethod
    def _check_gh_installed() -> bool:
        """Check if GitHub CLI is installed."""
        try:
            subprocess.run(
                ["gh", "--version"],
                capture_output=True,
                check=True
            )
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False

    @staticmethod
    def _check_gh_auth() -> bool:
        """Check if GitHub CLI is authenticated."""
        try:
            result = subprocess.run(
                ["gh", "auth", "status"],
                capture_output=True,
                text=True
            )
            return result.returncode == 0
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False
